### ISSUE TITLE
HTTP error : Too Many Requests (RFC 6585)

### ISSUE THREAD

**Issue by bioshot-dotcom** [cran/TheOpenAIR#1]
Hi!

Firstly, thank you for this project! Secondly, I get this error when I try to use this in my RStudio console.
`
> library(TheOpenAIR)
> openai_api_key('my-key')
> chat('Hi!')

HTTP error : Too Many Requests (RFC 6585)
Error in messages(.) : 
  Invalid parameter value. Expecting list or chatlog object.
`
I have no clue of what am I doing wrong, thank you!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
